/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Image;
import java.awt.Toolkit;

public class JF_Acceso extends javax.swing.JFrame {
    String puesto="";
    String interfaz;

    /**
     * Creates new form Acceso
     */
    public JF_Acceso(String interfazVariable) {
        initComponents();
        this.setLocationRelativeTo(null);
        interfaz=interfazVariable;
    }

    private JF_Acceso() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
     public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/PIZZA_TIME_LOGO2.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txt_Usuario = new javax.swing.JTextField();
        jL_CajaRedonda = new javax.swing.JLabel();
        jL_Bienvenido = new javax.swing.JLabel();
        jL_EscUsuario = new javax.swing.JLabel();
        jL_Logo = new javax.swing.JLabel();
        jL_NVersion = new javax.swing.JLabel();
        btn_Salir = new javax.swing.JLabel();
        btn_Entrar = new javax.swing.JLabel();
        jL_ImgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Usuario.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        txt_Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Usuario.setBorder(null);
        txt_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 380, -1));

        jL_CajaRedonda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_CajaRedonda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CajaTextoRedonda.png"))); // NOI18N
        jPanel2.add(jL_CajaRedonda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 600, -1));

        jL_Bienvenido.setFont(new java.awt.Font("Bauhaus 93", 1, 60)); // NOI18N
        jL_Bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        jL_Bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Bienvenido.setText("Bienvenido");
        jL_Bienvenido.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jL_Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 600, -1));

        jL_EscUsuario.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        jL_EscUsuario.setForeground(new java.awt.Color(0, 255, 207));
        jL_EscUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_EscUsuario.setText("Escribe tu número de usuario:");
        jPanel2.add(jL_EscUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 600, -1));

        jL_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PIZZA_TIME_LOGO.png"))); // NOI18N
        jPanel2.add(jL_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jL_NVersion.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jL_NVersion.setForeground(new java.awt.Color(255, 255, 255));
        jL_NVersion.setText("v 1.0.0");
        jPanel2.add(jL_NVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 670, -1, -1));

        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIR.png"))); // NOI18N
        btn_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SalirMouseClicked(evt);
            }
        });
        jPanel2.add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        btn_Entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Entrar.png"))); // NOI18N
        btn_Entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Entrar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btn_Entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EntrarMouseClicked(evt);
            }
        });
        jPanel2.add(btn_Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        jL_ImgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/700x600ACCESO.jpg"))); // NOI18N
        jL_ImgFondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jL_ImgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsuarioActionPerformed

    private void btn_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_SalirMouseClicked
    JF_Ordenes ordenes=new JF_Ordenes();
    JF_AdmEmpleados empleados=new JF_AdmEmpleados();
    JF_Ingredientes ingredientes=new JF_Ingredientes();
    JF_Pizzas pizzas=new JF_Pizzas();
    JF_Refrescos refresco=new JF_Refrescos();
    JF_Registro registro=new JF_Registro();
//    JF_Acceso acceso=new JF_Acceso();
    private void btn_EntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EntrarMouseClicked
        // TODO add your handling code here:
        Login l=new Login();
        puesto=l.existe(txt_Usuario.getText());
        if (interfaz.equals("Ordenes")) {
            if (puesto.equals("Gerente") || puesto.equals("Empleado")) {
                ordenes.setVisible(true);
                dispose();
            }
        }
        if (interfaz.equals("AdmEmpleados")) {
            if (puesto.equals("Gerente")) {
                empleados.setVisible(true);
                dispose();
            }
        }
        if (interfaz.equals("Ingredientes")) {
            if (puesto.equals("Gerente")) {
                ingredientes.setVisible(true);
                dispose();
            }
        }
        if (interfaz.equals("Modificar")) {
            if (puesto.equals("Gerente")) {
                ordenes.setVisible(true);
                dispose();
            }
        }
        if (interfaz.equals("Pizzas")) {
            if (puesto.equals("Gerente")) {
                pizzas.setVisible(true);
                dispose();
            }
        }
        if (interfaz.equals("Refrescos")) {
            if (puesto.equals("Gerente")) {
                refresco.setVisible(true);
                dispose();
            }
        }
        if (interfaz.equals("Registro")) {
            if (puesto.equals("Gerente")) {
                registro.setVisible(true);
                dispose();
            }
        }
        
    }//GEN-LAST:event_btn_EntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Acceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Entrar;
    private javax.swing.JLabel btn_Salir;
    private javax.swing.JLabel jL_Bienvenido;
    private javax.swing.JLabel jL_CajaRedonda;
    private javax.swing.JLabel jL_EscUsuario;
    private javax.swing.JLabel jL_ImgFondo;
    private javax.swing.JLabel jL_Logo;
    private javax.swing.JLabel jL_NVersion;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_Usuario;
    // End of variables declaration//GEN-END:variables
}
