/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author jlmlf
 */
public class JF_Ingredientes extends javax.swing.JFrame {
    
   
    
    /**
     * Creates new form JF_Ingredientes
     */
    public JF_Ingredientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        tabla();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jL_NombreInt = new javax.swing.JLabel();
        btn_AgrNuevo = new javax.swing.JLabel();
        btn_Borrar = new javax.swing.JLabel();
        btn_adm = new javax.swing.JLabel();
        btn_ordenes = new javax.swing.JLabel();
        btn_pizzas = new javax.swing.JLabel();
        btn_ingredientes = new javax.swing.JLabel();
        btn_refrescos = new javax.swing.JLabel();
        btn_Salir = new javax.swing.JLabel();
        jL_TNuevoIngrediente = new javax.swing.JLabel();
        jL_TNombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jL_TPrecio = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Ingredientes = new javax.swing.JTable();
        jL_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_NombreInt.setFont(new java.awt.Font("Bauhaus 93", 1, 60)); // NOI18N
        jL_NombreInt.setForeground(new java.awt.Color(0, 255, 255));
        jL_NombreInt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_NombreInt.setText("Ingredientes");
        jL_NombreInt.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jL_NombreInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 770, -1));

        btn_AgrNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgNuevo.png"))); // NOI18N
        btn_AgrNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_AgrNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AgrNuevoMouseClicked(evt);
            }
        });
        jPanel1.add(btn_AgrNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 610, -1, -1));

        btn_Borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Borrar.png"))); // NOI18N
        btn_Borrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BorrarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 610, -1, -1));

        btn_adm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_adm.png"))); // NOI18N
        btn_adm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_adm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_admMouseClicked(evt);
            }
        });
        jPanel1.add(btn_adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        btn_ordenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Ordenes.png"))); // NOI18N
        btn_ordenes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ordenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ordenesMouseClicked(evt);
            }
        });
        jPanel1.add(btn_ordenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        btn_pizzas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_pizzas.png"))); // NOI18N
        btn_pizzas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_pizzas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pizzasMouseClicked(evt);
            }
        });
        jPanel1.add(btn_pizzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        btn_ingredientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_ingredientes.png"))); // NOI18N
        btn_ingredientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ingredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ingredientesMouseClicked(evt);
            }
        });
        jPanel1.add(btn_ingredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, -1));

        btn_refrescos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button.png"))); // NOI18N
        btn_refrescos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_refrescos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_refrescosMouseClicked(evt);
            }
        });
        jPanel1.add(btn_refrescos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));

        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIR.png"))); // NOI18N
        btn_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SalirMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 720, -1, -1));

        jL_TNuevoIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jL_TNuevoIngrediente.setForeground(new java.awt.Color(255, 255, 0));
        jL_TNuevoIngrediente.setText("Nuevo Ingrediente");
        jPanel1.add(jL_TNuevoIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 140, -1, -1));

        jL_TNombre.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jL_TNombre.setForeground(new java.awt.Color(255, 255, 0));
        jL_TNombre.setText("Nombre:");
        jPanel1.add(jL_TNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 230, -1, -1));

        txt_nombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, 380, 60));

        jL_TPrecio.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jL_TPrecio.setForeground(new java.awt.Color(255, 255, 0));
        jL_TPrecio.setText("Precio");
        jPanel1.add(jL_TPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, -1, -1));

        txt_precio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 410, 380, 60));

        table_Ingredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Nombre", "Precio"
            }
        ));
        table_Ingredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_IngredientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_Ingredientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 670, 380));

        jL_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoIngredientes.jpg"))); // NOI18N
        jPanel1.add(jL_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Read r=new Read();
    Create c=new Create();
    Delete d=new Delete();
    
    private void tabla() {
        r.readCualquierTabla(table_Ingredientes, "T_ingredientes");
    }
    private void btn_AgrNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AgrNuevoMouseClicked
        // TODO add your handling code here:
        c.t_ingredientes(txt_nombre.getText(), txt_precio.getText());
        tabla();
        txt_nombre.setText("");
        txt_precio.setText("");
    }//GEN-LAST:event_btn_AgrNuevoMouseClicked

    private void btn_BorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BorrarMouseClicked
        // TODO add your handling code here:
        d.deleteingrediente("T_ingredientes", txt_nombre.getText());
        tabla();
        txt_nombre.setText("");
        txt_precio.setText("");
    }//GEN-LAST:event_btn_BorrarMouseClicked

    private void btn_admMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_admMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_admMouseClicked

    private void btn_ordenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ordenesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ordenesMouseClicked

    private void btn_pizzasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pizzasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pizzasMouseClicked

    private void btn_ingredientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingredientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingredientesMouseClicked

    private void btn_refrescosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refrescosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_refrescosMouseClicked

    private void btn_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SalirMouseClicked
        dispose();
    }//GEN-LAST:event_btn_SalirMouseClicked

    private void table_IngredientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_IngredientesMouseClicked
        // TODO add your handling code here:
        int fila=table_Ingredientes.getSelectedRow();
        //fila: le asignamos la variable con la fila
        //columna: en la posicion 0 esta nombre, 1 precio
        txt_nombre.setText(table_Ingredientes.getValueAt(fila, 0).toString());
        txt_precio.setText(table_Ingredientes.getValueAt(fila, 1).toString());
    }//GEN-LAST:event_table_IngredientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Ingredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Ingredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Ingredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Ingredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Ingredientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_AgrNuevo;
    private javax.swing.JLabel btn_Borrar;
    private javax.swing.JLabel btn_Salir;
    private javax.swing.JLabel btn_adm;
    private javax.swing.JLabel btn_ingredientes;
    private javax.swing.JLabel btn_ordenes;
    private javax.swing.JLabel btn_pizzas;
    private javax.swing.JLabel btn_refrescos;
    private javax.swing.JLabel jL_Fondo;
    private javax.swing.JLabel jL_NombreInt;
    private javax.swing.JLabel jL_TNombre;
    private javax.swing.JLabel jL_TNuevoIngrediente;
    private javax.swing.JLabel jL_TPrecio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_Ingredientes;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
