/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author jlmlf
 */
public class JF_Modificar extends javax.swing.JFrame {

    /**
     * Creates new form JF_Modificar
     */
    public JF_Modificar(String Id, String Nombre, String Apellidos, String Salario) {
        initComponents();
        this.setLocationRelativeTo(null);
        txt_nombre.setText(Nombre);
        txt_apellidos.setText(Apellidos);
        txt_salario.setText(Salario);
        etiquetaIdentificadora.setText(Id);
    }

    private JF_Modificar() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jL_empleado = new javax.swing.JLabel();
        jL_TNombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jL_TApellidos = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        jL_TPuesto = new javax.swing.JLabel();
        jComboBoxPuestos = new javax.swing.JComboBox<>();
        jL_TSalario = new javax.swing.JLabel();
        txt_salario = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JLabel();
        btn_Cancelar = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JLabel();
        jL_Fondo = new javax.swing.JLabel();
        etiquetaIdentificadora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/300x300Empleado.png"))); // NOI18N
        jPanel1.add(jL_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, -1, -1));

        jL_TNombre.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jL_TNombre.setForeground(new java.awt.Color(255, 255, 0));
        jL_TNombre.setText("Nombre:");
        jPanel1.add(jL_TNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        txt_nombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 380, 60));

        jL_TApellidos.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jL_TApellidos.setForeground(new java.awt.Color(255, 255, 0));
        jL_TApellidos.setText("Apellidos:");
        jPanel1.add(jL_TApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        txt_apellidos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 380, 60));

        jL_TPuesto.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jL_TPuesto.setForeground(new java.awt.Color(255, 255, 0));
        jL_TPuesto.setText("Puesto:");
        jPanel1.add(jL_TPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        jComboBoxPuestos.setEditable(true);
        jComboBoxPuestos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBoxPuestos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Gerente" }));
        jComboBoxPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPuestosActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxPuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 380, 60));

        jL_TSalario.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jL_TSalario.setForeground(new java.awt.Color(255, 255, 0));
        jL_TSalario.setText("Salario:");
        jPanel1.add(jL_TSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, -1, -1));

        txt_salario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(txt_salario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 380, 60));

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_guardar.png"))); // NOI18N
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 440, -1, -1));

        btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Btn_Cancelar.png"))); // NOI18N
        btn_Cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CancelarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, -1, -1));

        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_limpiar.png"))); // NOI18N
        btn_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_limpiarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 600, -1, -1));

        jL_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRegistro.jpg"))); // NOI18N
        jPanel1.add(jL_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        etiquetaIdentificadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(etiquetaIdentificadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 180, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Update u=new Update();
    
    private void limpiar(){
        txt_nombre.setText("");
        txt_apellidos.setText("");
        txt_salario.setText("");
    }
    private void btn_limpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limpiarMouseClicked
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btn_limpiarMouseClicked

    private void btn_CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CancelarMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_CancelarMouseClicked

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        // TODO add your handling code here:
        u.t_empleados(
                etiquetaIdentificadora.getText(), 
                txt_nombre.getText(), 
                txt_apellidos.getText(), 
                jComboBoxPuestos.getSelectedItem().toString(), 
                txt_salario.getText());
        limpiar();
    }//GEN-LAST:event_btn_guardarMouseClicked

    private void jComboBoxPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPuestosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPuestosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Cancelar;
    private javax.swing.JLabel btn_guardar;
    private javax.swing.JLabel btn_limpiar;
    private javax.swing.JLabel etiquetaIdentificadora;
    private javax.swing.JComboBox<String> jComboBoxPuestos;
    private javax.swing.JLabel jL_Fondo;
    private javax.swing.JLabel jL_TApellidos;
    private javax.swing.JLabel jL_TNombre;
    private javax.swing.JLabel jL_TPuesto;
    private javax.swing.JLabel jL_TSalario;
    private javax.swing.JLabel jL_empleado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_salario;
    // End of variables declaration//GEN-END:variables
}
