/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.JOptionPane;

/**
 *
 * @author jlmlf
 */
public class JF_Ordenes extends javax.swing.JFrame {

    /**
     * Creates new form JF_Ordenes
     */
    public JF_Ordenes() {
        initComponents();
        pizaRefresco = jComboBox.getSelectedItem().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_pizzas = new javax.swing.JLabel();
        btn_adm = new javax.swing.JLabel();
        btn_refrescos = new javax.swing.JLabel();
        btn_ingredientes = new javax.swing.JLabel();
        btn_ordenes = new javax.swing.JLabel();
        jL_TNombre2 = new javax.swing.JLabel();
        btn_Salir = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        btn_Ordenar = new javax.swing.JLabel();
        btn_Add = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_cargar = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtCantidad = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        btn_quitar = new javax.swing.JLabel();
        btn_Up = new javax.swing.JLabel();
        btn_Down = new javax.swing.JLabel();
        jL_TNombre1 = new javax.swing.JLabel();
        jL_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_pizzas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_pizzas.png"))); // NOI18N
        btn_pizzas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_pizzas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pizzasMouseClicked(evt);
            }
        });
        jPanel1.add(btn_pizzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        btn_adm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_adm.png"))); // NOI18N
        btn_adm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_adm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_admMouseClicked(evt);
            }
        });
        jPanel1.add(btn_adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        btn_refrescos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button.png"))); // NOI18N
        btn_refrescos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_refrescos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_refrescosMouseClicked(evt);
            }
        });
        jPanel1.add(btn_refrescos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, -1, -1));

        btn_ingredientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_ingredientes.png"))); // NOI18N
        btn_ingredientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ingredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ingredientesMouseClicked(evt);
            }
        });
        jPanel1.add(btn_ingredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, -1, -1));

        btn_ordenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Ordenes.png"))); // NOI18N
        btn_ordenes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ordenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ordenesMouseClicked(evt);
            }
        });
        jPanel1.add(btn_ordenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        jL_TNombre2.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        jL_TNombre2.setForeground(new java.awt.Color(255, 255, 255));
        jL_TNombre2.setText("Ticket");
        jL_TNombre2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jL_TNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 380, -1));

        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIR.png"))); // NOI18N
        btn_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SalirMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 710, -1, -1));

        jComboBox.setEditable(true);
        jComboBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona (Pizzas / Refrescos)", "Pizzas", "Refrescos" }));
        jComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxItemStateChanged(evt);
            }
        });
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 340, 40));

        jTextField1.setText("0");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 530, 90, 40));

        btn_Ordenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_ordenar.png"))); // NOI18N
        btn_Ordenar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Ordenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_OrdenarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Ordenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, -1, -1));

        btn_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_añadir.png"))); // NOI18N
        btn_Add.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AddMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 120, -1, -1));

        tabla_cargar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Ingrediente 1", "Ingrediente 2", "Orilla", "Tamaño", "Precio"
            }
        ));
        tabla_cargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_cargarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_cargar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 670, 380));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 380, 210));

        txtCantidad.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 50, 40));

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 70, 40));

        txtSubtotal.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        txtSubtotal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 70, 40));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, 40));

        btn_quitar.setForeground(new java.awt.Color(255, 255, 255));
        btn_quitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x.png"))); // NOI18N
        btn_quitar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_quitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_quitarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_quitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 50, -1));

        btn_Up.setForeground(new java.awt.Color(255, 255, 255));
        btn_Up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/up.png"))); // NOI18N
        btn_Up.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_UpMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Up, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 20, -1));

        btn_Down.setForeground(new java.awt.Color(255, 255, 255));
        btn_Down.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/down.png"))); // NOI18N
        btn_Down.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(btn_Down, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 20, -1));

        jL_TNombre1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        jL_TNombre1.setForeground(new java.awt.Color(255, 255, 255));
        jL_TNombre1.setText("Nombre             Cantidad     Precio     Subtotal");
        jPanel1.add(jL_TNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 420, -1));

        jL_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoOrdenes.jpg"))); // NOI18N
        jPanel1.add(jL_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Read r = new Read();
    Create c = new Create();
    Delete d = new Delete();
    ModeloComboBox m = new ModeloComboBox();
    String idProducto = null;
    String pizaRefresco = null;
    String idVenta;
    int fila;
    String id;
    int i = 0;
    int j = 0;

    String carrito[][] = new String[10][5];

    private void limpiar() {
        txtCantidad.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtSubtotal.setText("");
    }
    private void btn_pizzasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pizzasMouseClicked
        // TODO add your handling code here:
        JF_Acceso acceso = new JF_Acceso("Pizzas");
        acceso.setVisible(true);
    }//GEN-LAST:event_btn_pizzasMouseClicked

    private void btn_admMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_admMouseClicked
        // TODO add your handling code here:
        JF_Acceso acceso = new JF_Acceso("AdmEmpleados");
        acceso.setVisible(true);
    }//GEN-LAST:event_btn_admMouseClicked

    private void btn_refrescosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refrescosMouseClicked
        // TODO add your handling code here:
        JF_Acceso acceso = new JF_Acceso("Refrescos");
        acceso.setVisible(true);
    }//GEN-LAST:event_btn_refrescosMouseClicked

    private void btn_ingredientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingredientesMouseClicked
        // TODO add your handling code here:
        JF_Acceso acceso = new JF_Acceso("Ingredientes");
        acceso.setVisible(true);
    }//GEN-LAST:event_btn_ingredientesMouseClicked

    private void btn_ordenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ordenesMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_ordenesMouseClicked

    private void btn_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_SalirMouseClicked

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void btn_OrdenarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_OrdenarMouseClicked
        // TODO add your handling code here:
        if (!jTextField1.getText().equals("0")) {
            c.t_venta(jTextField1.getText());
            //obtener la id de esta venta
            idVenta = m.identificador();

            //Cambiamos la id de venta carrito[i][1]=idVenta+"";
            for (int k = 0; k < i; k++) {
                for (int l = 0; l < 5; l++) {
                    carrito[k][1] = idVenta;
                }
            }
            //leemos el carrito e insertamos venta
            for (int k = 0; k < i; k++) {

                if (carrito[k][0].equals("Pizzas")) {
                    c.t_ventas_pizzas(carrito[k][1], carrito[k][2], carrito[k][3], carrito[k][4]);
                }
                if (carrito[k][0].equals("Refrescos")) {
                    c.t_ventas_refrescos(carrito[k][1], carrito[k][2], carrito[k][3], carrito[k][4]);
                }
                //System.out.println(carrito[k][l]);

            }

            limpiar();
            jTextArea1.setText("");
            jTextField1.setText("0");
            JOptionPane.showMessageDialog(null, "Pedido recibido, imprimiendo recibo...");
            i = 0;
        }


    }//GEN-LAST:event_btn_OrdenarMouseClicked

    private void btn_AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddMouseClicked
        // TODO add your handling code here:
        if (txtNombre.getText() != "") {
            jTextArea1.setText(jTextArea1.getText()
                    + txtNombre.getText() + "      "
                    + txtCantidad.getText() + "      "
                    + txtPrecio.getText() + "      "
                    + txtSubtotal.getText() + "      identificador:"
                    + id + "      "
                    + "\n");
            float suma = Float.parseFloat(jTextField1.getText()) + Float.parseFloat(txtSubtotal.getText());
            jTextField1.setText(suma + "");

            if (pizaRefresco.equals("Pizzas")) {
                carrito[i][0] = "Pizzas";
                carrito[i][1] = idVenta;
                carrito[i][2] = id;
                carrito[i][3] = txtCantidad.getText();
                carrito[i][4] = txtSubtotal.getText();
                i++;
            }
            if (pizaRefresco.equals("Refrescos")) {
                carrito[i][0] = "Refrescos";
                carrito[i][1] = idVenta;
                carrito[i][2] = id;
                carrito[i][3] = txtCantidad.getText();
                carrito[i][4] = txtSubtotal.getText();
                i++;
            }

        }

        pizaRefresco = jComboBox.getSelectedItem().toString();
        if (pizaRefresco.equals("Pizzas")) {
            txtNombre.setText("Pizza");
            txtCantidad.setText("1");
            txtPrecio.setText(tabla_cargar.getValueAt(fila, 5).toString());
            float calculo = (Float.parseFloat(txtPrecio.getText()) * Float.parseFloat(txtCantidad.getText()));
            txtSubtotal.setText(calculo + "");
        }
        if (pizaRefresco.equals("Refrescos")) {
            txtNombre.setText("Refresco");
            txtCantidad.setText("1");
            txtPrecio.setText(tabla_cargar.getValueAt(fila, 3).toString());
            float calculo = (Float.parseFloat(txtPrecio.getText()) * Float.parseFloat(txtCantidad.getText()));
            txtSubtotal.setText(calculo + "");
        }
    }//GEN-LAST:event_btn_AddMouseClicked

    private void jComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxItemStateChanged
        // TODO add your handling code here:
        pizaRefresco = jComboBox.getSelectedItem().toString();
        if (pizaRefresco.equals("Pizzas")) {
            r.pizza(tabla_cargar);
        }
        if (pizaRefresco.equals("Refrescos")) {
            r.refresco(tabla_cargar);
        }
    }//GEN-LAST:event_jComboBoxItemStateChanged

    private void btn_quitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_quitarMouseClicked
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btn_quitarMouseClicked

    private void tabla_cargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_cargarMouseClicked
        // TODO add your handling code here:
        fila = tabla_cargar.getSelectedRow();
        id = tabla_cargar.getValueAt(fila, 0).toString();
    }//GEN-LAST:event_tabla_cargarMouseClicked

    private void btn_UpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpMouseClicked
        // TODO add your handling code here:
        int cantidad = Integer.parseInt(txtCantidad.getText());
        cantidad++;
        float calculo = Float.parseFloat(txtPrecio.getText()) * cantidad;
        txtCantidad.setText(cantidad + "");
        txtSubtotal.setText(calculo + "");
    }//GEN-LAST:event_btn_UpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Ordenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Ordenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Add;
    private javax.swing.JLabel btn_Down;
    private javax.swing.JLabel btn_Ordenar;
    private javax.swing.JLabel btn_Salir;
    private javax.swing.JLabel btn_Up;
    private javax.swing.JLabel btn_adm;
    private javax.swing.JLabel btn_ingredientes;
    private javax.swing.JLabel btn_ordenes;
    private javax.swing.JLabel btn_pizzas;
    private javax.swing.JLabel btn_quitar;
    private javax.swing.JLabel btn_refrescos;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jL_Fondo;
    private javax.swing.JLabel jL_TNombre1;
    private javax.swing.JLabel jL_TNombre2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabla_cargar;
    private javax.swing.JLabel txtCantidad;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtPrecio;
    private javax.swing.JLabel txtSubtotal;
    // End of variables declaration//GEN-END:variables
}
