/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author jlmlf
 */
public class JF_Pizzas extends javax.swing.JFrame {

    /**
     * Creates new form JF_Pizzas
     */
    public JF_Pizzas() {
        initComponents();
        this.setLocationRelativeTo(null);
        ModeloComboBox m=new ModeloComboBox();
        combobox_ingrediente1.setModel(m.getcalues());
        combobox_ingrediente2.setModel(m.getcalues());
        tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jL_NombreInt = new javax.swing.JLabel();
        btn_AgrNuevo = new javax.swing.JLabel();
        btn_Borrar = new javax.swing.JLabel();
        btn_adm = new javax.swing.JLabel();
        btn_ordenes = new javax.swing.JLabel();
        btn_pizzas = new javax.swing.JLabel();
        btn_ingredientes = new javax.swing.JLabel();
        btn_refrescos = new javax.swing.JLabel();
        btn_Salir = new javax.swing.JLabel();
        jL_TNuevaPizza = new javax.swing.JLabel();
        jL_TNombre = new javax.swing.JLabel();
        txt_tamaño = new javax.swing.JTextField();
        jL_TIng1 = new javax.swing.JLabel();
        combobox_ingrediente1 = new javax.swing.JComboBox<>();
        jL_TIng2 = new javax.swing.JLabel();
        combobox_ingrediente2 = new javax.swing.JComboBox<>();
        jL_TOrilla = new javax.swing.JLabel();
        jComboBoxOrilla = new javax.swing.JComboBox<>();
        jL_TPrecio = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_pizzas = new javax.swing.JTable();
        jL_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_NombreInt.setFont(new java.awt.Font("Bauhaus 93", 1, 60)); // NOI18N
        jL_NombreInt.setForeground(new java.awt.Color(0, 255, 255));
        jL_NombreInt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_NombreInt.setText("Pizzas");
        jL_NombreInt.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jL_NombreInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 770, -1));

        btn_AgrNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgNuevo.png"))); // NOI18N
        btn_AgrNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_AgrNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AgrNuevoMouseClicked(evt);
            }
        });
        jPanel1.add(btn_AgrNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 620, -1, -1));

        btn_Borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Borrar.png"))); // NOI18N
        btn_Borrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BorrarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 610, -1, -1));

        btn_adm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_adm.png"))); // NOI18N
        btn_adm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_adm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_admMouseClicked(evt);
            }
        });
        jPanel1.add(btn_adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        btn_ordenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_Ordenes.png"))); // NOI18N
        btn_ordenes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ordenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ordenesMouseClicked(evt);
            }
        });
        jPanel1.add(btn_ordenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        btn_pizzas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_pizzas.png"))); // NOI18N
        btn_pizzas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_pizzas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pizzasMouseClicked(evt);
            }
        });
        jPanel1.add(btn_pizzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        btn_ingredientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn_ingredientes.png"))); // NOI18N
        btn_ingredientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ingredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ingredientesMouseClicked(evt);
            }
        });
        jPanel1.add(btn_ingredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, -1));

        btn_refrescos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button.png"))); // NOI18N
        btn_refrescos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_refrescos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_refrescosMouseClicked(evt);
            }
        });
        jPanel1.add(btn_refrescos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));

        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIR.png"))); // NOI18N
        btn_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SalirMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 720, -1, -1));

        jL_TNuevaPizza.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jL_TNuevaPizza.setForeground(new java.awt.Color(255, 255, 0));
        jL_TNuevaPizza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_TNuevaPizza.setText("Nueva Pizza");
        jPanel1.add(jL_TNuevaPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 120, 460, -1));

        jL_TNombre.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jL_TNombre.setForeground(new java.awt.Color(255, 255, 0));
        jL_TNombre.setText("Tamaño:");
        jPanel1.add(jL_TNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 170, -1, -1));

        txt_tamaño.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(txt_tamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, 380, 40));

        jL_TIng1.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jL_TIng1.setForeground(new java.awt.Color(255, 255, 0));
        jL_TIng1.setText("Ingrediente 1:");
        jPanel1.add(jL_TIng1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 260, -1, -1));

        combobox_ingrediente1.setEditable(true);
        combobox_ingrediente1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        combobox_ingrediente1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combobox_ingrediente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_ingrediente1ActionPerformed(evt);
            }
        });
        jPanel1.add(combobox_ingrediente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 300, 380, 40));

        jL_TIng2.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jL_TIng2.setForeground(new java.awt.Color(255, 255, 0));
        jL_TIng2.setText("Ingrediente 2:");
        jPanel1.add(jL_TIng2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 350, -1, -1));

        combobox_ingrediente2.setEditable(true);
        combobox_ingrediente2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        combobox_ingrediente2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combobox_ingrediente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_ingrediente2ActionPerformed(evt);
            }
        });
        jPanel1.add(combobox_ingrediente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 390, 380, 40));

        jL_TOrilla.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jL_TOrilla.setForeground(new java.awt.Color(255, 255, 0));
        jL_TOrilla.setText("Orilla:");
        jPanel1.add(jL_TOrilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 440, -1, -1));

        jComboBoxOrilla.setEditable(true);
        jComboBoxOrilla.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBoxOrilla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sencilla", "Queso" }));
        jComboBoxOrilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOrillaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxOrilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 480, 380, 40));

        jL_TPrecio.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jL_TPrecio.setForeground(new java.awt.Color(255, 255, 0));
        jL_TPrecio.setText("Precio");
        jPanel1.add(jL_TPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 530, -1, -1));

        txt_precio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 570, 380, 40));

        table_pizzas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Tamaño", "Ingrediente 1", "Ingrediente 2", "Orilla", "Precio"
            }
        ));
        table_pizzas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_pizzasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_pizzas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 670, 380));

        jL_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPizzas.jpg"))); // NOI18N
        jPanel1.add(jL_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Read r=new Read();
    Create c=new Create();
    Delete d=new Delete();
    String id=null;
    
    private void tabla() {
        r.readCualquierTabla(table_pizzas, "T_pizzas");
        txt_tamaño.setText("");
        txt_precio.setText("");
    }
    private void btn_AgrNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AgrNuevoMouseClicked
        // TODO add your handling code here:
        c.t_pizzas(txt_tamaño.getText(), 
                combobox_ingrediente1.getSelectedItem().toString(), 
                combobox_ingrediente2.getSelectedItem().toString(), 
                jComboBoxOrilla.getSelectedItem().toString(), 
                txt_precio.getText());
        tabla();
    }//GEN-LAST:event_btn_AgrNuevoMouseClicked

    private void btn_BorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BorrarMouseClicked
        // TODO add your handling code here:
        d.deleteCualquierTabla("T_pizzas", id);
        tabla();
    }//GEN-LAST:event_btn_BorrarMouseClicked

    private void btn_admMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_admMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_admMouseClicked

    private void btn_ordenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ordenesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ordenesMouseClicked

    private void btn_pizzasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pizzasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pizzasMouseClicked

    private void btn_ingredientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingredientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingredientesMouseClicked

    private void btn_refrescosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refrescosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_refrescosMouseClicked

    private void btn_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SalirMouseClicked
        dispose();
    }//GEN-LAST:event_btn_SalirMouseClicked

    private void jComboBoxOrillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOrillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOrillaActionPerformed

    private void combobox_ingrediente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_ingrediente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_ingrediente2ActionPerformed

    private void combobox_ingrediente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_ingrediente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_ingrediente1ActionPerformed

    private void table_pizzasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_pizzasMouseClicked
        // TODO add your handling code here:
        int fila=table_pizzas.getSelectedRow();
        id=table_pizzas.getValueAt(fila, 0).toString();
    }//GEN-LAST:event_table_pizzasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Pizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Pizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Pizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Pizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Pizzas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_AgrNuevo;
    private javax.swing.JLabel btn_Borrar;
    private javax.swing.JLabel btn_Salir;
    private javax.swing.JLabel btn_adm;
    private javax.swing.JLabel btn_ingredientes;
    private javax.swing.JLabel btn_ordenes;
    private javax.swing.JLabel btn_pizzas;
    private javax.swing.JLabel btn_refrescos;
    private javax.swing.JComboBox<String> combobox_ingrediente1;
    private javax.swing.JComboBox<String> combobox_ingrediente2;
    private javax.swing.JComboBox<String> jComboBoxOrilla;
    private javax.swing.JLabel jL_Fondo;
    private javax.swing.JLabel jL_NombreInt;
    private javax.swing.JLabel jL_TIng1;
    private javax.swing.JLabel jL_TIng2;
    private javax.swing.JLabel jL_TNombre;
    private javax.swing.JLabel jL_TNuevaPizza;
    private javax.swing.JLabel jL_TOrilla;
    private javax.swing.JLabel jL_TPrecio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_pizzas;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_tamaño;
    // End of variables declaration//GEN-END:variables
}
